name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    strategy:
      matrix:
        runner: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Cleanup
        run: |
          sudo time -v rm -rf /usr/lib/jvm /usr/share/dotnet /usr/share/swift /usr/local/.ghcup \
                      /usr/local/julia* /usr/local/lib/android /usr/local/share/chromium \
                      /opt/microsoft /opt/google /opt/az /usr/local/share/powershell \
                      /opt/hostedtoolcache
          df -h
      
      - uses: cachix/install-nix-action@v31
      - uses: actions/checkout@v4
        with:
          repository: BasedLinux/bsdpkgs
          token: ${{ secrets.BSDPKGS_PAT }}
      
      - name: Cache
        run: |
          mkdir -p ~/.aws
          cat > ~/.aws/credentials << EOF
          [default]
          aws_access_key_id = ${{ secrets.WASABI_ACCESS_KEY }}
          aws_secret_access_key = ${{ secrets.WASABI_SECRET_KEY }}
          EOF
          cat > ~/.aws/config << EOF
          [default]
          region = us-east-1
          s3 = 
              endpoint_url = https://s3.wasabisys.com
          EOF
          
          sudo mkdir -p /etc/nix
          echo '${{ secrets.NIX_SIGNING_KEY_PRIVATE }}' | sudo tee /etc/nix/signing-key.sec > /dev/null
          sudo chmod 600 /etc/nix/signing-key.sec
          
          sudo tee /etc/nix/nix.conf << EOF
          substituters = https://s3.wasabisys.com/${{ secrets.WASABI_BUCKET }} https://cache.nixos.org/
          trusted-public-keys = ${{ secrets.NIX_SIGNING_KEY_PUBLIC }} cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          secret-key-files = /etc/nix/signing-key.sec
          post-build-hook = /etc/nix/upload-hook.sh
          EOF
          
          sudo tee /etc/nix/upload-hook.sh << 'EOF'
          #!/bin/bash
          set -eu
          export IFS=' '
          nix copy --to 's3://${{ secrets.WASABI_BUCKET }}?endpoint=s3.wasabisys.com&region=us-east-1' $OUT_PATHS 2>/dev/null || true
          EOF
          sudo chmod +x /etc/nix/upload-hook.sh
      
      - name: ISO
        run: |
          nix build .#install-iso
          nix-store --query --requisites ./result | xargs nix copy --to 's3://${{ secrets.WASABI_BUCKET }}?endpoint=s3.wasabisys.com&region=us-east-1'
          
      - name: System
        run: |
          [[ "${{ matrix.runner }}" == *"arm"* ]] && nixos-rebuild build --flake .#raspi || nixos-rebuild build --flake .#desktop
          nix copy --to 's3://${{ secrets.WASABI_BUCKET }}?endpoint=s3.wasabisys.com&region=us-east-1' ./result
